name: xenarchitecture
favicon: null
layout_spectrum: 0.9904113300144672
typography_spectrum: 0.8688805806450546
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.06396139063872397
  lightness: 0.7930349872913212
  saturation: 0.05108903953805566
  rhythmicContrast: 0.7233856706880033
purpose: []
